FROM golang:1.25-alpine@sha256:8e02eb337d9e0ea459e041f1ee5eece41cbb61f1d83e7d883a3e2fb4862063fa AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /sandbox-launcher ./cmd/sandbox-launcher

FROM alpine:3.18@sha256:de0eb0b3f2a47ba1eb89389859a9bd88b28e82f5826b6969ad604979713c2d4f
RUN apk --no-cache add ca-certificates
WORKDIR /sandbox-launcher
COPY --from=builder /sandbox-launcher /sandbox-launcher/sandbox-launcher
